version: '3'
services:
  mongodb:
    image: postgres
    restart: always
    ports:
      - 8080:8080
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/data/db
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5432:5432
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_EMAILPASSWORD=password
      #SERVER is set in pgadmin
    depends_on:
      - pgdb
  my-app:
    image: akshith6212/pgdb:1.0
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - pgdb
volumes:
  mongo-data:
    driver: local
